# Name of the Workflow, obligatory field, "name" is a keyword.
name: First Workflow  

# Defining event that triggers the whole Workflow, "on" is a keyword. Most of the triggers are repository related, but we also have others like:
# workflow_dispatch: manual trigger
# repository_dispatch:
# schedlue:
# workflow_call:
on: push  

# Defining jobs section, "jobs" is a keyword.
jobs:
  # Name of the first job, it can be anything, like variable.
  first-job:  
    # Defining runner for all steps, "runs-on" is a keyword, you can use Github-hosted runners or use custom ones.
    runs-on: ubuntu-latest  
    # Defining steps, "steps" is a keyword.
    steps:
      # Name of the step, "name" is a keyword, value is up to you, it must starts with the "-" sign.
      - name: Regular and simple step  
        run: echo "Hello World!"
        # Running multiple line shell commands
      - name: Multi-line step
        run: |
          echo "First line"
          echo "Second line"  
